language: php

php:
  - 5.5
  - 5.6

branches:
  only:
    - master

before_install:
  - 'composer self-update'
  - 'composer install'

script:
  - 'vendor/bin/phpunit --coverage-clover=coverage.clover'

after_success:
  - 'wget https://scrutinizer-ci.com/ocular.phar'
  - 'php ocular.phar code-coverage:upload --format=php-clover coverage.clover'
